import { Link } from "react-router-dom";
import { CapabilityState, Metric, OpsAssistant, Panel, RiskBadge, StateBadge } from "@/components/autonomy/AutoBits";
import { useAutonomyEventStream, useCapability, useAutonomySettings } from "@/hooks/autonomy/use-autonomy";
import { asRecord, num, str } from "@/lib/autonomy/platform";
import { formatDistanceToNow } from "date-fns";

const TILES: Array<{ key: string; label: string; tone?: "danger" | "warn" | "ok" }> = [
  { key: "active_coordinations", label: "Active Coordinations" },
  { key: "active_actors", label: "Active Autonomous Actors" },
  { key: "tasks_running", label: "Tasks Running", tone: "ok" },
  { key: "tasks_waiting", label: "Tasks Waiting", tone: "warn" },
  { key: "tasks_failed", label: "Tasks Failed", tone: "danger" },
  { key: "approvals_required", label: "Human Approvals Required", tone: "warn" },
  { key: "escalations", label: "Escalations", tone: "warn" },
  { key: "paused_operations", label: "Paused Operations", tone: "warn" },
  { key: "high_risk_operations", label: "High-Risk Operations", tone: "danger" },
  { key: "authority_expirations", label: "Authority Expirations" },
  { key: "kill_switch_recent", label: "Recent Kill-Switch Activity", tone: "danger" },
  { key: "autonomy_health", label: "Platform Autonomy Health" },
];

export default function OperationsOverview() {
  const [settings] = useAutonomySettings();
  const overview = useCapability<Record<string, unknown>>("operations.overview", {}, { refetchInterval: settings.refreshMs });
  const summary = asRecord(overview.data);
  const events = useAutonomyEventStream(15);

  return (
    <div className="space-y-4">
      <CapabilityState status={overview.status} message={overview.message} label="the operations overview">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {TILES.map((t) => {
            const raw = summary[t.key];
            const value = raw == null ? "—" : typeof raw === "number" ? raw : str(raw);
            return <Metric key={t.key} label={t.label} value={value} tone={num(raw) ? t.tone : undefined} />;
          })}
        </div>
        {summary.woic_summary && (
          <Panel title="WOIC Operational Summary" description="Generated by the cognitive core from live operations.">
            <p className="whitespace-pre-wrap text-sm">{str(summary.woic_summary)}</p>
          </Panel>
        )}
      </CapabilityState>

      <Panel
        title="Live Event Stream"
        description="Real production events from the Event Fabric. Simulation artifacts are never shown here."
        actions={<Link to="/autonomy/ledger" className="text-xs text-primary hover:underline">Open Autonomy Ledger</Link>}
      >
        {events.isLoading && <p className="text-sm text-muted-foreground">Loading events…</p>}
        {events.error && <p className="text-sm text-red-400">The Event Fabric could not be reached.</p>}
        {events.data && events.data.length === 0 && (
          <p className="text-sm text-muted-foreground">No operational events recorded for this organization.</p>
        )}
        <ul className="space-y-1">
          {(events.data ?? []).map((e) => (
            <li key={e.id} className="flex flex-wrap items-center gap-2 border-b py-1.5 text-sm last:border-0">
              <StateBadge state={asRecord(e.metadata).state} />
              <span className="font-mono text-xs text-muted-foreground">{e.module}</span>
              <span className="flex-1 truncate">{e.name}</span>
              <RiskBadge risk={asRecord(e.metadata).risk} />
              <span className="text-[11px] text-muted-foreground">
                {formatDistanceToNow(new Date(e.created_at), { addSuffix: true })}
              </span>
            </li>
          ))}
        </ul>
      </Panel>

      <OpsAssistant context={{ overview: summary, recent_events: (events.data ?? []).slice(0, 15) }} />
    </div>
  );
}
