// Signs a document template on behalf of the authenticated worker.
// - Validates JWT and worker identity
// - Loads active template + current version
// - Computes SHA-256 of the rendered body + signer identity
// - Records document_signatures row with IP/UA metadata
// The rendered PDF is generated by the existing generate-pdf function on demand.

import { createClient } from "npm:@supabase/supabase-js@2";
import * as Sentry from "npm:@sentry/deno";
import { requireUser, jsonResponse, unauthorizedResponse } from "../_shared/auth.ts";

const SENTRY_DSN = Deno.env.get("SENTRY_DSN");
if (SENTRY_DSN) Sentry.init({ dsn: SENTRY_DSN, tracesSampleRate: 0 });

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

async function sha256(text: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const authHeader = req.headers.get("Authorization") ?? "";
    if (!/^Bearer\s+\S/i.test(authHeader)) return unauthorizedResponse(corsHeaders);

    const auth = await requireUser(req, corsHeaders);
    if (auth instanceof Response) return auth;
    const { user } = auth;

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    const body = await req.json().catch(() => ({}));
    const { template_id, typed_name } = body as { template_id?: string; typed_name?: string };
    if (!template_id || !typed_name || typed_name.trim().length < 2) {
      return jsonResponse({ error: "template_id and typed_name are required", code: "bad_input" }, 400, corsHeaders);
    }

    const admin = createClient(supabaseUrl, serviceKey);

    // Resolve worker for this user
    const { data: worker, error: wErr } = await admin
      .from("workers")
      .select("id, agency_id")
      .eq("user_id", user.id)
      .maybeSingle();
    if (wErr || !worker) return jsonResponse({ error: "forbidden", code: "forbidden" }, 403, corsHeaders);

    // Load active template + current version
    const { data: tmpl, error: tErr } = await admin
      .from("document_templates")
      .select("id, agency_id, status, body_markdown")
      .eq("id", template_id)
      .single();
    if (tErr || !tmpl) return jsonResponse({ error: "template not found", code: "not_found" }, 404, corsHeaders);
    if (tmpl.status !== "active") return jsonResponse({ error: "template not active", code: "bad_state" }, 409, corsHeaders);
    if (tmpl.agency_id !== worker.agency_id) return jsonResponse({ error: "forbidden", code: "forbidden" }, 403, corsHeaders);

    const { data: version } = await admin
      .from("document_versions")
      .select("id, version_number, body_markdown")
      .eq("template_id", template_id)
      .order("version_number", { ascending: false })
      .limit(1)
      .maybeSingle();

    const contentToHash = [
      tmpl.id,
      version?.id ?? "",
      version?.body_markdown ?? tmpl.body_markdown ?? "",
      worker.id,
      typed_name.trim(),
    ].join("\n");
    const contentSha = await sha256(contentToHash);

    const ip = req.headers.get("x-forwarded-for") ?? null;
    const ua = req.headers.get("user-agent") ?? null;

    const { data: sig, error: sErr } = await admin
      .from("document_signatures")
      .insert({
        agency_id: worker.agency_id,
        worker_id: worker.id,
        template_id: tmpl.id,
        version_id: version?.id ?? null,
        typed_name: typed_name.trim(),
        content_sha256: contentSha,
        ip_address: ip,
        user_agent: ua,
      })
      .select("id, signed_at, content_sha256")
      .single();
    if (sErr) throw sErr;

    return jsonResponse({ ok: true, signature: sig }, 200, corsHeaders);
  } catch (err) {
    Sentry.captureException(err);
    const message = err instanceof Error ? err.message : "internal error";
    return jsonResponse({ error: message, code: "internal_error" }, 500, corsHeaders);
  }
});
